name: SPW4 Test Runner Demo

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn compile