name: SPW4 Test Runner Demo

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn compile
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ~/target
      - uses: actions/cache@v4
        with:
          path: ~/target
          key: build-cache-${{ github.run_id }}
          restore-keys: build-cache-

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-cache-${{ github.run_id }}
          path: target/*
      - name: Test with Maven
        run: mvn test